# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "swarm_manager", primary: true do |swarm_manager|
    swarm_manager.vm.box = "debian/contrib-stretch64"
    swarm_manager.vm.hostname = 'swarm-manager'
    swarm_manager.vm.box_check_update = false
    swarm_manager.vm.synced_folder ".", "/vagrant_data"

    swarm_manager.vm.network :private_network, ip: "192.168.56.101"

    swarm_manager.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "swarm_manager"]
    end
  end

  config.vm.define "swarm_worker" do |swarm_worker|
    swarm_worker.vm.box = "debian/contrib-stretch64"
    swarm_worker.vm.hostname = 'swarm-worker'
    swarm_worker.vm.box_check_update = false
    swarm_worker.vm.synced_folder ".", "/vagrant_data"

    swarm_worker.vm.network :private_network, ip: "192.168.56.102"

    swarm_worker.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "swarm_worker"]
    end
  end

  config.vm.provision "shell", :path => "docker.sh"
  config.vm.define "swarm_worker", autostart: false
end
